project_id = "uphlmknketudkycsfkah"

[functions.generate-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = true

[functions.check-pix-payment]
verify_jwt = true

[functions.manage-credits]
verify_jwt = true

[functions.check-signup-limit]
verify_jwt = false

[functions.log-signup]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.webhook-mercadopago]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = true
